# debug is Enable debug logs --> true is spring boot logs but too many so this project false
debug: false

management.endpoints.web.exposure.include: "*"

logging:
  level:
    org.example.board: debug
    org.springframework.web.servlet: debug # request, response logging
#    org.hibernate.SQL: debug # nested logging with -> org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: hooneats
    password: hooneats
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql version is higher than 8
  jpa:
    database: mysql # mysql dialect
#    defer-datasource-initialization: true # this defer-DB(test db), use for higher than version spring boot 2.5
    hibernate.ddl-auto: create
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
#  sql.init.mode: always # test data insert initialization by data.sql
#  thymeleaf.cache: false
#  data.rest:
#    base-path: /api
#    detection-strategy: annotated

---

spring:
  config.activate.on-profile: testdb # equals before properties is 'profiles.active'

#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none

